# Load all needed packages
library(rmarkdown)
library(ggpubr)
library(ggplot2)
library(ggrepel)
library(STRAND)
library(igraph)
library(foreach)
library(doSNOW)
library(ANTs)
library(parallel)
library(doParallel)
library(bisonR)
library(bayestestR)
